# SPDX-FileCopyrightText: Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
  - package-ecosystem: composer
    directory: "/socialsharing_bluesky/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
  - package-ecosystem: composer
    directory: "/socialsharing_diaspora/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
  - package-ecosystem: composer
    directory: "/socialsharing_email/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
  - package-ecosystem: composer
    directory: "/socialsharing_facebook/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
  - package-ecosystem: composer
    directory: "/socialsharing_telegram/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
  - package-ecosystem: composer
    directory: "/socialsharing_twitter/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
  - package-ecosystem: composer
    directory: "/socialsharing_whatsapp/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10